# Generated by Django 3.2.2 on 2021-05-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210513_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='login',
            name='hashed_password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
