# Generated by Django 3.2.2 on 2021-05-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
