# Generated by Django 3.2.2 on 2021-05-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='value',
            field=models.IntegerField(default=123, unique=True),
        ),
    ]
