# Generated by Django 3.2.2 on 2021-05-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_number_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
