# Generated by Django 3.2.2 on 2021-05-13 22:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=api.models.generate_random_number),
        ),
    ]
